sudo: false
language: python
matrix:
  include:
    - python: "3.5"
      env: LTD_MASON_BUILD=true
install:
  - pip install -r requirements.txt
  - pip install "ltd-mason>=0.2,<0.3"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd-mason-travis --html-dir _build/html
env:
  global:
    - LTD_MASON_BUILD=false  # disable builds in regular text matrix
    - LTD_MASON_PRODUCT="{{ cookiecutter.series.lower() }}-{{ cookiecutter.serial_number }}"
    # Add AWS and LTD Keeper credentials as encrypted secrets here

