sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-000
